services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sakila-db
      - DB_USER=sakila
      - DB_PASSWORD=p_ssW0rd
      - DB_NAME=sakila
      - DB_PORT=3306
      - NODE_ENV=production
    depends_on:
      - sakila-db
    networks:
      - sakila-network

  sakila-db:
    image: sakiladb/mysql:latest
    ports:
      - "13306:3306"
    networks:
      - sakila-network

networks:
  sakila-network:
    driver: bridge

volumes:
  sakila-data: